networks:
  monitoring:
    name: monitoring
    driver: bridge
    
services:

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail 
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-amd64:v0.50.0
    platform: linux/amd64
    container_name: cadvisor
    hostname: ${SERVER_NAME}-${ENVIRONMENT}-cadvisor
    labels:
      - "server=${SERVER_NAME}"
      - "environment=${ENVIRONMENT}"
      - "service=cadvisor"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    ports:
      - "8081:8080"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: ${SERVER_NAME}-${ENVIRONMENT}-node-exporter
    labels:
      - "server=${SERVER_NAME}"
      - "environment=${ENVIRONMENT}"
      - "service=node-exporter"
    ports:
      - "9100:9100"
    networks:
      - monitoring
